[package]
name = "solana-snapshot-etl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
log = "0.4.17"
env_logger = "0.9.0"
solana-runtime = "1.11.1"
thiserror = "1.0.31"
bincode = "1.3.3"
solana-sdk = "1.11.1"
serde = { version = "1.0.137", features = ["derive"] }
indicatif = "0.17.0-rc.11"
memmap2 = "0.5.4"
ouroboros = "0.15.0"
itertools = "0.10.3"
