[package]
name = "solana-snapshot-etl"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
log = "0.4.17"
solana-runtime = "1.11.1"
thiserror = "1.0.31"
bincode = "1.3.3"
serde = { version = "1.0.137", features = ["derive"] }
solana-sdk = "1.11.1"
memmap2 = "0.5.4"
itertools = "0.10.3"

# Binary deps
csv = { version = "1.1.6", optional = true }
env_logger = { version = "0.9.0", optional = true }
indicatif = { version = "0.17.0-rc.11", optional = true }

[features]
standalone = ["csv", "env_logger", "indicatif"]

[[bin]]
name = "solana-snapshot-etl"
required-features = ["standalone"]
